title_name = "Angry Birds: Star Wars"
title_id = "41560901" # AV-2305
hash = "0FE4DAF1B7659591" # default.xex
#media_id = "116000C4" # Disc (USA, Europe): http://redump.org/disc/46912

[[patch]]
    name = "Fixed Multiplayer Menu Crashing"
    author = "Adrian"
    is_enabled = false

    [[patch.be16]]
        address = 0x826fe3b2
        value = 0x0000
