title_name = "Pirates of the Caribbean: At World’s End"
title_id = "425607D1"
hash = "1FCB4BC2DAD834A3"

[[patch]]
    name = "60 FPS"
    desc = "Unlocks frame rate to 60 FPS"
    author = "tronuo"
    is_enabled = false

[[patch.be32]]
        address = 0x822B5750
        value = 0x3BA00001
