title_name = "Deadly Premonition"
title_id = "494F07D4" # IO-2004
hash = "439D4F4A66F41F9B" # default.xex
#media_id = "5E4E45E2" # Disc (USA): http://redump.org/disc/14704

[[patch]]
    name = "60 FPS"
    desc = "Requires "vsync = true" or "framerate_limit = 60". The patch makes the game render one frame per vblank and removes the in game limiter. Without vsync or a framelimit, the game goes beyond 60fps and runs extremely fast."
    author = "ehw"
    is_enabled = false

    [[patch.be32]]
        address = 0x8252a274
        value = 0x48000020

    [[patch.be32]]
        address = 0x8252a2a0
        value = 0x2b0b0001
