title_name = "Kameo: Elements of Power"
title_id = "4D5307D2" # MS-2002
hash = "1A83A0AF5C0EDFE8" # default.xex
#media_id = "45BB5521" # Disc (Europe): redump.org/disc/8561

[[patch]]
    name = "60 FPS + Camera Fix"
    desc = "Enables 60 FPS and fixes automatic camera following. Do not enable with 100 FPS + Camera Fix. Requires vsync = true and framerate_limit = 60."
    author = "Margen67, ISpectre23"
    is_enabled = false

    [[patch.be8]]
        address = 0x820cf93f
        value = 0x01
    [[patch.be32]]
        address = 0x82440f18
        value = 0xc0bf0084
    [[patch.be32]]
        address = 0x82440f20
        value = 0xefbde82a
    [[patch.be32]]
        address = 0x82440f34
        value = 0xd0b90008

[[patch]]
    name = "100 FPS + Camera Fix"
    desc = "Enables 100 FPS and fixes automatic camera following. Do not enable with 60 FPS + Camera Fix. Requires vsync = true and framerate_limit = 100."
    author = "Margen67, ISpectre23"
    is_enabled = false

    [[patch.be8]]
        address = 0x820cf93f
        value = 0x01
    [[patch.be32]]
        address = 0x82440f18
        value = 0xc0bf0084
    [[patch.be32]]
        address = 0x82440f20
        value = 0xc31ac1a8
    [[patch.be32]]
        address = 0x82440f34
        value = 0xd0b90008
    [[patch.be32]]
        address = 0x82440f74
        value = 0xefbfc024
    [[patch.be32]]
        address = 0x82440f7c
        value = 0xc1bafff8

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in the README."
    author = "Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x82087cac
        value = 0x4018e38e
