title_name = "Fable II" # 2, GOTY (Game Of The Year)/Platinum Edition, TU1
title_id = "4D5307F1" # MS-2033
hash = "EE56F849188A6A20" # default.xex
#media_id = "716F0A0D" # Disc (USA, Europe): https://redump.info/disc/20202

[[patch]]
    name = "60 FPS"
    author = "illusion"
    is_enabled = false

    [[patch.be32]]
        address = 0x82ba3018
        value = 0x39600001

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 1120x720."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x823894c2
        value = 0x0500

[[patch]]
    name = "Disable MSAA (Multi-Sample Anti-Aliasing)"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x823894a7
        value = 0x01

[[patch]]
    name = "Disable Texture Morphing"
    desc = "Workaround for the dog's & hero's broken textures. Makeup is still bugged. Can make morphs look strange."
    author = "Guy, Ultra"
    is_enabled = false

    [[patch.be16]]
        address = 0x8220edd8
        value = 0x4280

[[patch]]
    name = "High Tick Rate"
    desc = "Doubles tickrate LF to 30Hz, HF to 60Hz retains 2:1 scheduler ratio. Vastly improves UI and input delay."
    author = "Guy, Ultra"
    is_enabled = false

    [[patch.be32]]
        address = 0x8231091c
        value = 0x60000000
    [[patch.be8]]
        address = 0x83319661
        value = 0x3e
    [[patch.be32]]
        address = 0x82310900
        value = 0x60000000
    [[patch.be8]]
        address = 0x83319669
        value = 0x4e

[[patch]]
    name = "Unlock Website Items"
    desc = "Unlocks the Guild chest containing the items that were obtainable from the Fable 2 website."
    author = "Guy, Ultra"
    is_enabled = false

    [[patch.be8]]
        address = 0x8253b1d3
        value = 0x01
    [[patch.be32]]
        address = 0x8253b1a8
        value = 0x42800028

[[patch]]
    name = "Unlock Collectors Edition Content"
    desc = "Unlocks Hal's items in the Guild chest, and enables the Hall of the Dead dungeon."
    author = "Guy, Ultra"
    is_enabled = false

    [[patch.be32]]
        address = 0x824edcf4
        value = 0x39200001

[[patch]]
    name = "High Tick Rate Stairs & Ledge Fix"
    desc = "Forces Havok's hkpCharacterProxy::integrate function to use 1 substep during character update to respect higher LF tick rates."
    author = "Ultra"
    is_enabled = false

    [[patch.be32]]
        address = 0x82e487e4
        value = 0x39600001
