title_name = "Kameo: Elements of Power (TU2)"
title_id = "4D5307D2" # MS-2002
hash = "B94D3AB68548DF97" # default.xex
#media_id = "45BB5521" # Disc (Europe): redump.org/disc/8561

[[patch]]
    name = "60 FPS"
    desc = "Runs the game at 60 FPS with vsync = true and framerate_limit = 0. Higher framerates can be selected with framerate_limit. Use with the FPS Camera Fix."
    author = "Margen67, ICUP321"
    is_enabled = false

    [[patch.be8]]
        address = 0x820d17c7
        value = 0x01

[[patch]]
    name = "FPS Camera Fix"
    desc = "Fixes automatic camera following at higher and variable framerates. Enable when running above 30 FPS."
    author = "ISpectre23"
    is_enabled = false

    [[patch.be32]]
        address = 0x82493198
        value = 0xc0bf0084
    [[patch.be32]]
        address = 0x824931a0
        value = 0xc31b112c
    [[patch.be32]]
        address = 0x824931b4
        value = 0xd0b90008
    [[patch.be32]]
        address = 0x82493208
        value = 0xec40c024
    [[patch.be32]]
        address = 0x82493210
        value = 0xc1bf007c
    [[patch.be32]]
        address = 0x82493214
        value = 0xc19f0080
    [[patch.be32]]
        address = 0x82493218
        value = 0xed1a6828
    [[patch.be32]]
        address = 0x82493220
        value = 0xecca2828
    [[patch.be32]]
        address = 0x82493224
        value = 0xec6628ba
    [[patch.be32]]
        address = 0x82493228
        value = 0xd0790008
    [[patch.be32]]
        address = 0x8249322c
        value = 0xeca868ba
    [[patch.be32]]
        address = 0x82493230
        value = 0xd0b90000
    [[patch.be32]]
        address = 0x82493234
        value = 0xec87603a
    [[patch.be32]]
        address = 0x82493238
        value = 0xd0990004

[[patch]]
    name = "Aspect Ratio"
    desc = "See note about aspect ratio patches in the README."
    author = "Margen67, ICUP321"
    is_enabled = false

    [[patch.be32]]
        address = 0x82089cec
        value = 0x4018e38e
