title_name = "SOULCALIBUR V"
title_id = "4E4D083D" # NM-2109
hash = "22FA243E64C97C2E" # default.xex TU1
#media_id = "165FAD4F" # Disc (World): https://redump.info/disc/43237

[[patch]]
    name = "Reduce input lag"
    desc = "Reduce the delay of your button presses by 2 frames in all offline modes. This works by completely disabling the forced 'Practice with Frame Delay' system listed in Training."
    author = "WAZAAAAA"
    is_enabled = false

    [[patch.be32]]
        address = 0x8216e63c
        value = 0x39000000 # aob:7D26582E7D06282E->7D26582E39000000
